module NeuralFish.Exceptions
exception NodeRecordTypeException of string
exception NeuronInstanceException of string
exception NoBiasInRecordForNeuronException of string
exception SensorRecordDoesNotHaveASyncFunctionException of string
exception ActuatorRecordDoesNotHaveAOutputHookIdException of string
exception ShuffleDataRandomOptionIsNoneException of string
exception DataSetDoesNotHaveIndexException of int
exception NeuronInstanceUnavailableException of string
exception NeuronDoesNotHaveAnActivationFunction of string
exception MissingInboundConnectionException of string
exception NodeRecordMissingOutboundConnection of string
